alias ..="cd .."
alias n="nnn -C"
alias ls="ls --color=auto -h --group-directories-first -I 'node_modules'"
alias l="ls -l"
alias t="tree -I node_modules --dirsfirst"
alias grep="grep --color -i"
alias clip="xclip -sel clipboard -i"
alias y="youtube-dl --output ~/Downloads/%(title)s.%(ext)s"
